name: Simulate setting ARG_MAX

on: [push]

jobs:
  run-argmax:
    runs-on: ubuntu-latest
    steps:
      - name: Get and echo ARG_MAX
        run: |
          original_arg_max=$(getconf ARG_MAX)
          echo "Original ARG_MAX: $original_arg_max"
          
          # Simulating adding a '0' to the value
          simulated_arg_max="${original_arg_max}0"
          echo "Simulated ARG_MAX (with added 0): $simulated_arg_max"
